version: '3'
services:
  app_mgt:
    image: registry.cn-shenzhen.aliyuncs.com/epipepro/app_mgt
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == test01
    ports:
      - '80:8080'
    volumes:
      - app_mgt_logs:/usr/local/tomcat/logs
  app_api:
    image: registry.cn-shenzhen.aliyuncs.com/epipepro/app_member
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == test01
    ports:
      - '18080:8080'
    volumes:
      - app_api_logs:/usr/local/tomcat/logs
 
  app_service:
    image: registry.cn-shenzhen.aliyuncs.com/epipepro/app_service
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == test01
    volumes:
      - app_service_logs:/usr/local/tomcat/logs
     


networks:
  default:
    external:
      name: basic

volumes:
  app_mgt_logs:
  app_api_logs:
  app_service_logs:
